# Base bootc image
FROM ghcr.io/ublue-os/base-main:latest

# Install required packages
RUN \
--mount=type=cache,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-beardy-os-latest,sharing=locked \
--mount=type=cache,dst=/var/cache/libdnf5,id=dnf-cache-beardy-os-latest,sharing=locked \
dnf5 -y install glibc-locale-source glibc-langpack-en osbuild-selinux && \
dnf5 -y copr enable gmaglione/podman-bootc && \
dnf5 -y install podman-bootc && \
ostree container commit

RUN localedef -i en_US -f UTF-8 en_US.UTF-8
RUN echo "LANG=\"en_US.UTF-8\"" > /etc/locale.conf
RUN ln -s -f /usr/share/zoneinfo/America/New_York /etc/localtime

# Install additional packages
RUN \
--mount=type=cache,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-beardy-os-latest,sharing=locked \
--mount=type=cache,dst=/var/cache/libdnf5,id=dnf-cache-beardy-os-latest,sharing=locked \
dnf5 -y install \
cockpit-bridge \
cockpit-machines \
cockpit-navigator \
cockpit-networkmanager \
cockpit-ostree \
cockpit-podman \
cockpit-selinux \
cockpit-storaged \
cockpit-system \
podman-compose \
libvirt-client \
virt-install \
btrfs-assistant \
btrfsmaintenance \
dbus-daemon \
dbus-tools \
fastfetch \
ptyxis \
setroubleshoot-plugins \
setroubleshoot-server \
usermode \
virt-install \
virt-manager \
virt-what \
xdg-user-dirs \
xdg-user-dirs-gtk \
tig \
libguestfs \
&& ostree container commit

RUN bootc container lint

# bluebuild: Labels are added last since they cause cache misses with buildah
LABEL org.blue-build.build-id="c74bf003-e98a-4ac0-8db2-8869239c6c13"
LABEL org.opencontainers.image.title="beardy-os"
LABEL org.opencontainers.image.description="The preferred u-blue based OS for bearded developers."
LABEL org.opencontainers.image.base.digest="sha256:4ff605c93dca3a99b434f7363f400925685432cc22c5affbef9567e97d49603d"
LABEL org.opencontainers.image.base.name="ghcr.io/ublue-os/silverblue-main:latest"
LABEL org.opencontainers.image.created="2024-12-10T01:22:13.918756743+00:00"
LABEL io.artifacthub.package.readme-url=https://raw.githubusercontent.com/detiber/beardy-os/main/README.md
LABEL org.opencontainers.image.source=https://github.com/detiber/beardy-os
LABEL org.opencontainers.image.url=https://github.com/detiber/beardy-os
LABEL org.opencontainers.image.vendor=detiber
