name: bluebuild
on:
  push:
    branches:
      - main
    paths:
      - "artifacthub-repo.yml"
  workflow_dispatch: # allow manually triggering builds
concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  artifacthub-repo-metadata:
    name: Update artifacthub repo metadata
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container

      - name: Setup ORAS
        uses: oras-project/setup-oras@v1

      - run: oras version

      # TODO: remove hardcoded values here
      - run: oras push ghcr.io/detiber/beardy-os:artifacthub.io --config /dev/null:application/vnd.cncf.artifacthub.config.v1+yaml artifacthub-repo.yml:application/vnd.cncf.artifacthub.repository-metadata.layer.v1.yaml

