name: Latest Images
on:
  merge_group:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "50 5 * * 1,2,3,4,5,6" # 5:50 UTC All But Sunday (1 hour after bluefin)
    - cron: "50 5 * * 0" # 5:50 UTC Sunday (1 hour after bluefin)
  workflow_call:
  workflow_dispatch:

jobs:
  build-image-latest:
    name: Build Latest Images
    uses: ./.github/workflows/bluefin-reusable-build.yml

    permissions:
        contents: read
        packages: write
        id-token: write

    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        brand_name: ["beardy-bluefin"]
    with:
      image_flavors: '["main"]'
      brand_name: ${{ matrix.brand_name }}
      stream_name: latest
